version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    environment:
      - SA_PASSWORD=${SA_PASSWORD} # Retrieves password from .env file
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    # volumes:
    #   # - sqlserverdata:/var/opt/mssql # Uncomment this line and volumes to persist data
    #   - ./init.sql:/init.sql
    #   - ./entrypoint.sh:/entrypoint.sh
    # command: ["sh", "/entrypoint.sh"]
    env_file:
          - .env

# volumes: 
#   sqlserverdata:
    